name: stroke_cnn
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - appdirs=1.4.4
  - astunparse=1.6.3
  - attrs=23.2.0
  - black=23.7.0
  - blinker=1.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.2.0
  - cryptography=42.0.5
  - cycler=0.12.1
  - docker-pycreds=0.4.0
  - flatbuffers=23.5.26
  - fonttools=4.50.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gast=0.4.0
  - giflib=5.2.1
  - gitdb=4.0.11
  - gitpython=3.1.42
  - google-auth=2.28.2
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - grpcio=1.54.3
  - h5py=3.10.0
  - hdf5=1.14.3
  - icu=72.1
  - idna=3.6
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - jax=0.4.14
  - jaxlib=0.4.14
  - joblib=1.3.2
  - kaleido-core=0.2.1
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.6.0
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgrpc=1.54.3
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libpng=1.6.43
  - libprotobuf=3.21.12
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=18.1.1
  - markdown=3.6
  - markupsafe=2.1.5
  - mathjax=2.7.7
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - ml_dtypes=0.3.2
  - multidict=6.0.5
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - ncurses=6.4.20240210
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.2.1
  - opt_einsum=3.3.0
  - packaging=24.0
  - pandas=2.1.0
  - pathspec=0.12.1
  - pathtools=0.1.2
  - patsy=0.5.6
  - pillow=10.0.0
  - pip=24.0
  - platformdirs=4.2.0
  - plotly=5.19.0
  - protobuf=4.21.12
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.9.0
  - python-flatbuffers=24.3.7
  - python-kaleido=0.2.1
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - re2=2023.03.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.4.0
  - rsa=4.9
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sentry-sdk=1.42.0
  - setproctitle=1.3.3
  - setuptools=69.2.0
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.1.10
  - statsmodels=0.14.0
  - tenacity=8.2.3
  - tensorboard=2.12.3
  - tensorboard-data-server=0.7.0
  - tensorflow=2.12.1
  - tensorflow-base=2.12.1
  - tensorflow-estimator=2.12.1
  - termcolor=2.4.0
  - threadpoolctl=3.3.0
  - tk=8.6.13
  - tornado=6.4
  - typing_extensions=4.5.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wandb=0.15.10
  - werkzeug=3.0.1
  - wheel=0.42.0
  - wrapt=1.16.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - docopt==0.6.2
    - future==0.18.3
    - innvestigate==2.1.1
    - pipreqs==0.4.13
    - yarg==0.1.9
